/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ContentRootInterface extends utils.Interface {
  functions: {
    "createCollection(uint256,string,string)": FunctionFragment;
    "ownerIdToCollection(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createCollection" | "ownerIdToCollection"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerIdToCollection",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerIdToCollection",
    data: BytesLike
  ): Result;

  events: {
    "CollectionCreated(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;
}

export interface CollectionCreatedEventObject {
  ownerId: BigNumber;
  collectionAddress: string;
}
export type CollectionCreatedEvent = TypedEvent<
  [BigNumber, string],
  CollectionCreatedEventObject
>;

export type CollectionCreatedEventFilter =
  TypedEventFilter<CollectionCreatedEvent>;

export interface ContentRoot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ContentRootInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createCollection(
      ownerId: PromiseOrValue<BigNumberish>,
      collectionName: PromiseOrValue<string>,
      collectionSymbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ownerIdToCollection(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createCollection(
    ownerId: PromiseOrValue<BigNumberish>,
    collectionName: PromiseOrValue<string>,
    collectionSymbol: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ownerIdToCollection(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createCollection(
      ownerId: PromiseOrValue<BigNumberish>,
      collectionName: PromiseOrValue<string>,
      collectionSymbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    ownerIdToCollection(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "CollectionCreated(uint256,address)"(
      ownerId?: null,
      collectionAddress?: null
    ): CollectionCreatedEventFilter;
    CollectionCreated(
      ownerId?: null,
      collectionAddress?: null
    ): CollectionCreatedEventFilter;
  };

  estimateGas: {
    createCollection(
      ownerId: PromiseOrValue<BigNumberish>,
      collectionName: PromiseOrValue<string>,
      collectionSymbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ownerIdToCollection(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createCollection(
      ownerId: PromiseOrValue<BigNumberish>,
      collectionName: PromiseOrValue<string>,
      collectionSymbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ownerIdToCollection(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
